name: ci testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Restore Ubuntu cache
        uses: actions/cache@v1
        if: matrix.operating-system == 'ubuntu-latest'
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')}}
          restore-keys: ${{ matrix.os }}-${{ matrix.python-version }}-
      - name: Restore MacOS cache
        uses: actions/cache@v1
        if: matrix.operating-system == 'macos-latest'
        with:
          path: ~/Library/Caches/pip
          key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')}}
          restore-keys: ${{ matrix.os }}-${{ matrix.python-version }}-
      - name: Restore Windows cache
        uses: actions/cache@v1
        if: matrix.operating-system == 'windows-latest'
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')}}
          restore-keys: ${{ matrix.os }}-${{ matrix.python-version }}-
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install  numpy and matplotlib for Python 3.6
        if: matrix.python-version == 3.6
        run: >
          pip install "numpy>=1.18.5,<1.20" "matplotlib>=3.2.2,<4"
      - name: Install dependencies
        run: >
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
          python -m unittest
      - name: Test scripts
        run: |
          pip install -e .
          di=cpu # inference devices  # define device
          # train
            
          python train.py --workers 8 --device 0 --batch-size 32 --data data/coco.yaml --img 640 640 --cfg cfg/training/yolov7.yaml --weights '' --name yolov7 --hyp data/hyp.scratch.p5.yaml
          yolov7 train --workers 8 --device 0 --batch-size 32 --data data/coco.yaml --img 640 640 --cfg cfg/training/yolov7.yaml --weights '' --name yolov7 --hyp data/hyp.scratch.p5.yaml
          
          # detect / inference
          
          #python yolov5/detect.py --weights yolov5/weights/yolov5n.pt --device $di
          #yolov5 detect --weights yolov5/weights/yolov5n.pt --device $di
          #python yolov5/detect.py --weights runs/train/exp/weights/last.pt --device $di
          #yolov5 detect --weights runs/train/exp/weights/last.pt --device $di
          
          python yolov7/detect.py --weights yolov7/weights/yolov7.pt --conf 0.25 --img-size 640 --source yourvideo.mp4
          yolov7 detect --weights yolov7/weights/yolov7.pt --conf 0.25 --img-size 640 --source yourvideo.mp4
          
          # test/val
          #python yolov5/val.py --img 128 --batch 16 --weights yolov5/weights/yolov5n.pt --device $di
          #yolov5 val --data yolov5/data/coco128.yaml --img 128 --batch 16 --weights yolov5/weights/yolov5n.pt --device $di
          #python yolov5/val.py --img 128 --batch 16 --weights runs/train/exp/weights/last.pt --device $di
          #yolov5 val --data yolov5/data/coco128.yaml --img 128 --batch 16 --weights runs/train/exp/weights/last.pt --device $di
          
          python yolov7/test.py --data data/coco.yaml --img 640 --batch 32 --conf 0.001 --iou 0.65 --device 0 --weights yolov7.pt --name yolov7_640_val
          yolov7 test --data data/coco.yaml --img 640 --batch 32 --conf 0.001 --iou 0.65 --device 0 --weights yolov7.pt --name yolov7_640_val
          
          # export
          
          #pip install onnx onnx-simplifier tensorflowjs
          #python yolov5/export.py --weights yolov5/weights/yolov5n.pt --device $di --include 'torchscript,onnx,tflite'
          #yolov5 export --weights yolov5/weights/yolov5n.pt --device $di --simplify --include 'torchscript,onnx,saved_model,pb,tfjs'
          
          python export.py --weights yolov7-tiny.pt --grid --end2end --simplify --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 640 --max-wh 640
          yolov7 yolov7/export yolov7-tiny.pt --grid --end2end --simplify --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 640 --max-wh 640
